modLoader = "aplp"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheSilkMiner/APLPKIGB/issues"
[[mods]]
modId = "paint"
version = "${file.jarVersion}"
displayName = "Paint Stuff"
logoFile = "logo.png"
authors = "TheSilkMiner"
description = "The Grooviest language provider in Forge!"
[[dependencies.paint]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.paint]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

