modLoader = "aplp"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheSilkMiner/APLPKIGB/issues"
[[mods]]
modId = "austin"
version = "${file.jarVersion}"
displayName = "Austin's Powerful Language Provider"
logoFile = "logo.png"
authors = "TheSilkMiner"
description = "The Grooviest language provider in Forge!"
[[dependencies.austin]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.austin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"

